resources:
  - name: sample_ppp
    type: gitRepo
    repoPath: bindushree16/test1
    configuration:
      integrationName: bindu_github
      branches:
        only: master
    initialVersion:
      sha: master
      
pipelines:
  - name: pipeline11
    steps:
      - name: testpipelines
        type: bash
        configuration:
          chronological: false 
#           priority: 2
        triggeredBy:
          resources:
            - sample_ppp
        execution:
          onExecute:
            - printenv
            - echo "hi"
            
      - name: testpipel
        type: bash 
        triggeredBy:
          steps:
            - testpipelines
        execution:
          onExecute:
            - echo "hi"
            - node --version
